### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by TopGun666** [ducha-aiki/pytorch-sift#1]
Hi @ducha-aiki 

Could you please upload the pretrained model? Thanks a lot.

Regards,

Yu

**Comment by ducha-aiki** [comment]
Hi,

It is algorithmic descriptor, there is no such things as training here. Please, read the paper carefully 
https://www.cs.ubc.ca/~lowe/papers/ijcv04.pdf
 It is just implemented in pytorch.
