### ISSUE TITLE
How to replace OpenCV SIFT results with pytorch-sift

### ISSUE THREAD

**Issue by HtutLynn** [ducha-aiki/pytorch-sift#3]
Hello, I am trying to replace opencv sift which is used to generate keypoints and descriptions with pytorch-sift because of batch inference capability. 

```
sift = cv2.SIFT_create(contrastThreshold=-10000, edgeThreshold=-10000)
```

If possible, can you please guide me on this? Thanks in advance!

**Comment by ducha-aiki** [comment]
Unfortunately no. There is a SIFT detector in kornia https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.SIFTFeature, but it is much worse than OpenCV as for the detector part. 

So - no solution for your question now.
